name: CI
on:
  schedule:
  - cron: "45 3 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run sh
      run: |
        env | sort
        ls -la
    - name: Docker hook
      env:
        DOCKER_SOURCE: ${{ secrets.DOCKER_SOURCE_TEST }}
        DOCKER_TRIGGER: ${{ secrets.DOCKER_TRIGGER_TEST }}
      run: echo curl -X POST https://hub.docker.com/api/build/v1/source/${DOCKER_SOURCE}/trigger/${DOCKER_TRIGGER}/call/
