name: CI
on:
  schedule:
  - cron: "45 3 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run sh
      run: |
        env | sort
        ls -la
