name: CI
on:
  schedule:
  - cron: "45 3 * * 1-5"
  workflow_dispatch:
    inputs:
      deploy_group:
        description: Group name in ansible inventory file
        required: true
        default: dev
      deploy_state:
        description: "One of the states: staging, current, restore, absent, balancer, sync, test"
        required: true
        default: staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run sh
      env:
        DEPLOY_GROUP: ${{ github.event.inputs.deploy_group }}
        DEPLOY_STATE: ${{ github.event.inputs.deploy_state }}
      run: |
        env | sort
        ls -la
